spring:
  profiles:
    active: dev #默认为开发环境
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #驼峰命名自动识别配置

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: qiuzhidi-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7) 一周
  tokenHead: Bearer  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /memberAddress/**
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /uploads/**
      - /appVersion/**
      - /ipl/**

 #自定义redis key
redis:
  database: keshe
  key:
    authCode: 'ums:authCode'
    member: 'ums:member'
    cruit: 'cms:cruit'
    company: 'cms:company'


  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时

#分页插件
pagehelper:
  auto-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
