spring:
  profiles:
    active: dev #默认为开发环境
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #驼峰命名自动识别配置

 #自定义redis key
redis:
  database: keshe
  key:
    authCode: 'ums:authCode'
    member: 'ums:member'
    cruit: 'cms:cruit'
    company: 'cms:company'


#分页插件
pagehelper:
  auto-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
